# Generated by Django 2.2.28 on 2022-10-25 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_addressbfdkxhdpei'),
    ]

    operations = [
        migrations.AddField(
            model_name='addressbfdkxhdpei',
            name='ca',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
